version: "3"

networks:
  user-management:

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    tty: true
    networks:
      - user-management
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf/:ro
      - ./web:/web
    depends_on:
      - php
      - mysql
    ports:
      - 80:80
      - 443:443

  php:
    image: public.ecr.aws/r1c8s2z8/book-app-docker-demo:1.6
    container_name: php
    tty: true
    working_dir: /web
    volumes:
      - ./web:/web
      - ./conf:/conf
    networks:
      - user-management

  mysql:
    image: mysql:latest
    container_name: mysql
    tty: true
    networks:
      - user-management
    volumes:
      - ./mysql:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - 33601:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
